[package]
name = "performance_review"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.6", features = ["web"] }
dioxus-web = "0.5.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"