
# Dioxus.toml
[application]
name = "github_io"
default_platform = "web"
toolchain = "wasm"
out_dir = "target/d-dist"
serve_dir = "target/d-dist"

[web.app]
title = "Eric Machmer"

[web.resource]
# Include the '/' at the start of the file path below to ensure pages in subdirectories like 'essays' properly reference the css file
style = ["/assets/styles/tailwind.css"] # This is injected into the head of the index.html document
script = []

[web.resource.dev]
script = []

