[build]
target = "index.html"
dist = "dist"
public_url = "/"

[serve]
port = 8080

[[hooks]]
stage = "build"
command = "mkdir"
command_arguments = ["-p", "dist/static/css", "dist/static/images"]

[[hooks]]
stage = "build"
command = "cp"
command_arguments = ["-r", "public/images/", "dist/static/images/"]

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["cp public/css/index.css dist/static/css/"]


