[build]
target = "index.html"
dist = "dist"
public_url = "/"
wasm_opt = ["-O3"]

[serve]
port = 8080

[lib]
name = "githubio"
path = "src/lib.rs"

[[scss]]
from = "src/styles/styles.scss"
to = "static/css/index.css"

